builders:
  preferences_builder:
    import: "package:liblymph_gen/builder.dart"
    builder_factories: ["preferencesBuilder"]
    build_extensions: {"^assets/data/preferences.json": ["lib/generated/preferences.dart"]}
    auto_apply: dependents
    build_to: source

  locale_data_builder:
    import: "package:liblymph_gen/builder.dart"
    builder_factories: ["localeDataBuilder"]
    build_extensions: {
      "^assets/data/locales/{{}}/strings.xml": [
        "lib/generated/locale/data/{{}}.dart",
      ],
    }
    auto_apply: dependents
    build_to: source

  locale_builder:
    import: "package:liblymph_gen/builder.dart"
    builder_factories: ["localeBuilder"]
    build_extensions: {
      "$package$": [
        "lib/generated/locale/strings.dart",
        "lib/generated/locale/data.dart",
        "lib/generated/locale.dart",
      ],
    }
    auto_apply: dependents
    build_to: source